#! /bin/bash

echo "Filename AverageX AverageY stddevX stddevY TotalDev"
for i in ${@}
do
	echo -n $(./script1-01 $i | tail -n 1 | awk '{print $1,$2,$3,$4,$5}')
	x=$(./script1-01 $i | tail -n 1 | awk '{print $4}')
	y=$(./script1-01 $i | tail -n 1 | awk '{print $5}')
	averagedev=$(echo "sqrt(($x*$x)+($y*$y))" | bc)
	echo -n " "
	echo $averagedev
done
