#! /bin/bash

echo "filename		Average deviation"
for i in ${@}
do
	echo -n "$i	"
	x=$(./script1 $i | tail -n 1 | awk '{print $4}')
	y=$(./script1 $i | tail -n 1 | awk '{print $5}')
	averagedev=$(echo "sqrt(($x*$x)+($y*$y))" | bc)
	echo $averagedev
done
